name: Deploy to GitHub Pages
on:
    push:
        branches:
        - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Build
          run: |
            npm install
            npm run-script build
          env:
            SP2022_SITE_SS: ${{ secrets.sp2022_site_ss }}

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            BRANCH: main
            FOLDER: /(root)
